// ── Shared fake data for fellis.eu ──

// Deterministic color from name
export function nameToColor(name) {
  let hash = 0
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash)
  }
  const colors = ['#2D6A4F', '#40916C', '#52B788', '#1877F2', '#6C63FF', '#E07A5F', '#D4A574', '#81B29A', '#3D405B', '#F2CC8F']
  return colors[Math.abs(hash) % colors.length]
}

export function getInitials(name) {
  return name.split(' ').map(n => n[0]).join('')
}

// Current user
export const CURRENT_USER = {
  name: 'Sofie Nielsen',
  handle: '@sofie.nielsen',
  initials: 'SN',
  bio: { da: 'Grafisk designer fra København. Elsker kaffe, kunst og lange gåture.', en: 'Graphic designer from Copenhagen. Loves coffee, art and long walks.' },
  location: 'København, Danmark',
  joinDate: '2026-01-15T10:30:00.000Z',
  friendCount: 312,
  postCount: 847,
  photoCount: 2341,
  email: 'sofie@fellis.eu',
  loginMethod: 'email',
  createdAt: '2026-01-15T10:30:00.000Z',
}

// Friends
export const FRIENDS = [
  { name: 'Sofie Nielsen', mutual: 24, online: true },
  { name: 'Magnus Jensen', mutual: 18, online: true },
  { name: 'Freja Andersen', mutual: 31, online: false },
  { name: 'Emil Larsen', mutual: 12, online: true },
  { name: 'Ida Pedersen', mutual: 27, online: false },
  { name: 'Oscar Christensen', mutual: 9, online: true },
  { name: 'Alma Hansen', mutual: 22, online: true },
  { name: 'Viktor Mortensen', mutual: 15, online: false },
  { name: 'Clara Johansen', mutual: 33, online: true },
  { name: 'Noah Rasmussen', mutual: 7, online: false },
  { name: 'Astrid Poulsen', mutual: 19, online: true },
  { name: 'Liam Madsen', mutual: 11, online: false },
]

// Feed posts
export const POSTS = [
  {
    id: 1,
    author: 'Sofie Nielsen',
    time: { da: '2 timer siden', en: '2 hours ago' },
    text: { da: 'Endelig er mit nye designprojekt færdigt! Så glad for at dele det med jer alle her på fellis.eu 🎨', en: 'Finally my new design project is done! So happy to share it with everyone here on fellis.eu 🎨' },
    likes: 47,
    comments: [
      { author: 'Magnus Jensen', text: { da: 'Det ser fantastisk ud! 🔥', en: 'Looks amazing! 🔥' } },
      { author: 'Clara Johansen', text: { da: 'Wow, du er så talentfuld!', en: 'Wow, you are so talented!' } },
    ],
  },
  {
    id: 2,
    author: 'Magnus Jensen',
    time: { da: '4 timer siden', en: '4 hours ago' },
    text: { da: 'Nogen der vil med til koncert i Vega i næste uge? Har en ekstra billet!', en: 'Anyone want to come to a concert at Vega next week? I have an extra ticket!' },
    likes: 23,
    comments: [
      { author: 'Emil Larsen', text: { da: 'Ja tak! Hvem spiller?', en: 'Yes please! Who is playing?' } },
      { author: 'Alma Hansen', text: { da: 'Jeg er med! 🎵', en: "I'm in! 🎵" } },
      { author: 'Oscar Christensen', text: { da: 'Skriv mig op som reserve!', en: 'Put me down as backup!' } },
    ],
  },
  {
    id: 3,
    author: 'Freja Andersen',
    time: { da: '6 timer siden', en: '6 hours ago' },
    text: { da: 'Smukkeste solnedgang over Nyhavn i dag. København, du er smuk! ☀️', en: 'Most beautiful sunset over Nyhavn today. Copenhagen, you are beautiful! ☀️' },
    likes: 89,
    comments: [
      { author: 'Ida Pedersen', text: { da: 'Savner København så meget!', en: 'Miss Copenhagen so much!' } },
    ],
  },
  {
    id: 4,
    author: 'Alma Hansen',
    time: { da: '8 timer siden', en: '8 hours ago' },
    text: { da: 'Lige færdig med at læse "Smilla\'s fornemmelse for sne" for tredje gang. Stadig lige så god! 📚 Nogen der har boganbefalinger?', en: 'Just finished reading "Smilla\'s Sense of Snow" for the third time. Still just as good! 📚 Anyone have book recommendations?' },
    likes: 34,
    comments: [
      { author: 'Viktor Mortensen', text: { da: 'Prøv "Fasandræberne" af Jussi Adler-Olsen!', en: 'Try "The Pheasant Killers" by Jussi Adler-Olsen!' } },
      { author: 'Astrid Poulsen', text: { da: 'Elsker den bog! Prøv også Helle Helle.', en: 'Love that book! Also try Helle Helle.' } },
    ],
  },
  {
    id: 5,
    author: 'Clara Johansen',
    time: { da: '12 timer siden', en: '12 hours ago' },
    text: { da: 'Ny opskrift testet: Rugbrødsburger med remoulade og sprøde løg. Dommen: 10/10 ville lave igen! 🍔', en: 'New recipe tested: Rye bread burger with remoulade and crispy onions. The verdict: 10/10 would make again! 🍔' },
    likes: 56,
    comments: [
      { author: 'Noah Rasmussen', text: { da: 'Del venligst opskriften!', en: 'Please share the recipe!' } },
      { author: 'Sofie Nielsen', text: { da: 'Det lyder helt vildt godt!', en: 'That sounds absolutely amazing!' } },
      { author: 'Liam Madsen', text: { da: 'Rugbrød gør alt bedre 🙌', en: 'Rye bread makes everything better 🙌' } },
    ],
  },
  {
    id: 6,
    author: 'Oscar Christensen',
    time: { da: '1 dag siden', en: '1 day ago' },
    text: { da: 'Første dag på den nye cykelrute langs kysten. 45 km og benene er færdige, men udsigten var det hele værd! 🚴‍♂️', en: 'First day on the new coastal bike route. 45 km and my legs are done, but the view was worth it! 🚴‍♂️' },
    likes: 41,
    comments: [
      { author: 'Magnus Jensen', text: { da: 'Stærkt! Hvilken rute?', en: 'Strong! Which route?' } },
    ],
  },
  {
    id: 7,
    author: 'Ida Pedersen',
    time: { da: '1 dag siden', en: '1 day ago' },
    text: { da: 'Så glad for at være skiftet væk fra de store techplatforme. Her på fellis.eu føles det som om mine data faktisk er mine! 💚', en: 'So happy to have switched away from the big tech platforms. Here on fellis.eu it feels like my data is actually mine! 💚' },
    likes: 112,
    comments: [
      { author: 'Freja Andersen', text: { da: 'Enig! Bedste beslutning i år.', en: 'Agreed! Best decision this year.' } },
      { author: 'Alma Hansen', text: { da: 'Velkommen! Du vil elske det her ❤️', en: 'Welcome! You will love it here ❤️' } },
      { author: 'Emil Larsen', text: { da: '100% enig. EU-hostet og krypteret!', en: '100% agreed. EU-hosted and encrypted!' } },
    ],
  },
]

// Platform translations
export const PT = {
  da: {
    feed: 'Feed',
    profile: 'Profil',
    friends: 'Venner',
    messages: 'Beskeder',
    navBrand: 'fellis.eu',
    langToggle: 'EN',
    newPost: 'Hvad har du på hjerte?',
    postInputHint: 'Skriv et opslag\nEnter → Opslå  •  Shift+Enter → Ny linje\nIndsæt billeder med Ctrl+V',
    msgInputHint: 'Skriv en besked\nEnter → Send  •  Shift+Enter → Ny linje',
    post: 'Opslå',
    like: 'Synes godt om',
    comment: 'Kommentar',
    share: 'Del',
    writeComment: 'Skriv en kommentar...',
    send: 'Send',
    friendsTitle: 'Dine venner',
    online: 'Online',
    offline: 'Offline',
    mutualFriends: 'fælles venner',
    message: 'Besked',
    editProfile: 'Rediger profil',
    joined: 'Medlem siden',
    postsLabel: 'Opslag',
    photosLabel: 'Fotos',
    friendsLabel: 'Venner',
    loginInfo: 'Loginoplysninger',
    emailLabel: 'E-mail',
    loginMethodLabel: 'Loginmetode',
    accountCreatedLabel: 'Konto oprettet',
    loginMethodEmail: 'E-mail & adgangskode',
    loginMethodFacebook: 'Facebook',
    passwordLabel: 'Adgangskode',
    showPassword: 'Vis Kode',
    hidePassword: 'Skjul Kode',
    showPasswordHint: 'Vis Kode Hint',
    hidePasswordHint: 'Skjul Kode Hint',
    passwordNotSet: 'Ikke oprettet (Facebook-login)',
    search: 'Søg',
    searchPlaceholder: 'Søg i dine opslag og beskeder...',
    searchHint: 'Søg i opslag du har skrevet, synes godt om eller kommenteret, og i dine samtaler.',
    searchPostsTitle: 'Opslag',
    searchMessagesTitle: 'Beskeder',
    searchNoResults: 'Ingen resultater',
    searchGoToFeed: 'Se i feed',
    searchGoToConv: 'Åbn samtale',
    messagesTitle: 'Beskeder',
    typeMessage: 'Skriv en besked...',
    noMessages: 'Vælg en samtale for at starte',
    newMessage: 'Ny besked',
    newGroup: 'Ny gruppe',
    newConvTitle: 'Ny besked',
    newGroupTitle: 'Opret gruppe',
    groupNamePlaceholder: 'Gruppenavn (valgfrit)...',
    startConv: 'Start samtale',
    createGroup: 'Opret gruppe',
    invitePeople: 'Tilføj folk',
    inviteTitle: 'Tilføj til samtale',
    inviteBtn: 'Tilføj',
    muteConv: 'Sluk notifikationer',
    unmuteConv: 'Slå notifikationer til',
    muteTitle: 'Sluk notifikationer i...',
    mute1h: '1 time',
    mute8h: '8 timer',
    mute24h: '24 timer',
    mute1w: '1 uge',
    muteOff: 'Slå fra',
    mutedLabel: 'Slukket',
    renameGroup: 'Omdøb gruppe',
    renameTitle: 'Omdøb gruppe',
    renameBtn: 'Gem',
    leaveGroup: 'Forlad gruppe',
    leaveConfirm: 'Er du sikker på, at du vil forlade denne gruppe?',
    participants: 'deltagere',
    addedToGroup: 'Tilføjet til gruppe',
    familyGroup: 'Familie-gruppe',
    familyGroupToggle: 'Markér som Familie-gruppe',
    familyGroupInfo: 'Kun til inviterede · Skjult fra søgning · Opslag kan ikke deles videre',
    familyBadge: '🏡 Familie',
    familySection: 'Familie',
    familySectionDesc: 'Vises kun for godkendte familieforbindelser',
    familyNoGroups: 'Ingen familie-grupper endnu. Opret en gruppe og markér den som Familie.',
    familyPostNotShareable: 'Opslag fra familie-grupper kan ikke deles uden for gruppen.',
    selectFriends: 'Vælg venner',
    cancel: 'Annuller',
    convMenu: 'Samtaleindstillinger',
    allFriends: 'Alle venner',
    onlineFriends: 'Online',
    searchFriends: 'Søg efter brugere...',
    addFriend: 'Tilføj ven',
    friendAdded: 'Ven tilføjet',
    findPeople: 'Find brugere',
    connectRequest: 'Send forbindelsesanmodning',
    requestSent: 'Anmodning sendt',
    requestReceived: 'Vil forbindes',
    acceptRequest: 'Accepter',
    declineRequest: 'Afvis',
    incomingRequests: 'Forbindelsesanmodninger',
    unfriend: 'Fjern ven',
    unfriendConfirm: 'Fjern som ven?',
    unfriendSilent: 'Fjern stille (ingen besked)',
    unfriendNotify: 'Fjern og send besked',
    backToLanding: 'Tilbage til landing',
    // Account mode
    modeTitle: 'Vælg kontotype',
    modeCommon: 'Privat',
    modeBusiness: 'Erhverv',
    modeCommonDesc: 'Til personlig brug, familie og fællesskab',
    modeBusinessDesc: 'Til professionelt netværk og virksomhedsnærvær',
    modeSelect: 'Vælg',
    modeSwitch: 'Skift kontotype',
    modeCurrentLabel: 'Kontotype',
    modeCommonTag: 'Privat konto',
    modeBusinessTag: 'Erhvervskonto',
    // Business-mode labels (Venner → Forbindelser)
    connectionsTitle: 'Dine forbindelser',
    connectionsLabel: 'Forbindelser',
    allConnections: 'Alle forbindelser',
    connectBtn: 'Forbind',
    // Business profile fields
    titleLabel: 'Titel',
    companyLabel: 'Virksomhed',
    industryLabel: 'Branche',
    skillsLabel: 'Kompetencer',
    // Notifications
    notifications: 'Notifikationer',
    markAllRead: 'Markér alle som læst',
    noNotifications: 'Ingen notifikationer',
    notifFriendRequest: 'sendte dig en venneanmodning',
    notifConnectionRequest: 'sendte dig en forbindelsesanmodning',
    notifLike: 'synes godt om dit opslag',
    notifComment: 'kommenterede på dit opslag',
    notifAccepted: 'accepterede din venneanmodning',
    notifConnectionAccepted: 'accepterede din forbindelsesanmodning',
    notifGroupPost: 'delte et nyt opslag i',
    notifProfileView: 'besøgte din profil',
    notifEndorsement: 'anbefalede dine kompetencer',
    // Events
    events: 'Begivenheder',
    eventsTitle: 'Begivenheder',
    myEvents: 'Mine begivenheder',
    discoverEvents: 'Opdag',
    createEvent: 'Opret begivenhed',
    eventGoing: 'Deltager',
    eventMaybe: 'Måske',
    eventNotGoing: 'Deltager ikke',
    eventAttendees: 'deltagere',
    eventMaybes: 'måske',
    eventLocation: 'Sted',
    eventDate: 'Dato & tid',
    eventDescription: 'Beskrivelse',
    eventCover: 'Forsidebillede (valgfrit)',
    eventTitle: 'Titel',
    eventCreate: 'Opret begivenhed',
    eventCancel: 'Annuller',
    eventRsvp: 'Tilmeld dig',
    eventOrganizer: 'Arrangør',
    eventShare: 'Del begivenhed',
    eventNoUpcoming: 'Ingen kommende begivenheder',
    // Common-mode RSVP extras
    eventDietary: 'Kostbehov (valgfrit)',
    eventPlusOne: 'Medbring én gæst (+1)',
    // Business-mode event fields
    eventType: 'Begivenhedstype',
    eventTypeConference: 'Konference',
    eventTypeWebinar: 'Webinar',
    eventTypeWorkshop: 'Workshop',
    eventTypeMeetup: 'Meetup',
    eventTicketUrl: 'Tilmeldingslink / billetter',
    eventCap: 'Max. antal deltagere',
    eventCapPlaceholder: 'Ingen begrænsning',
    // Feed event card
    eventFeedLabel: 'Begivenhed',
    eventFeedRsvpd: 'deltager',
    eventFeedCreated: 'har oprettet en begivenhed',
    // Company pages
    companies: 'Virksomhedssider',
    myCompanies: 'Mine sider',
    followingCompanies: 'Følger',
    createCompany: 'Opret virksomhedsside',
    companyName: 'Virksomhedsnavn',
    companyTagline: 'Tagline',
    companyWebsite: 'Hjemmeside',
    companyIndustry: 'Branche',
    companySize: 'Størrelse',
    companyDescription: 'Beskrivelse',
    companyFollow: 'Følg',
    companyUnfollow: 'Afholg',
    companyFollowers: 'følgere',
    companyPosts: 'Opslag',
    companyAbout: 'Om',
    companyRoleOwner: 'Ejer',
    companyRoleAdmin: 'Admin',
    companyRoleEditor: 'Redaktør',
    companyRoleViewer: 'Seer',
    companyPost: 'Skriv et opslag...',
    companySizes: ['1–10', '11–50', '51–200', '201–500', '500+'],
    companyCreate: 'Opret side',
    companyCancel: 'Annuller',
    companySearchPlaceholder: 'Søg virksomheder...',
    companyFeedLabel: 'Virksomhedsside',
    // Jobs (business mode)
    jobs: 'Job',
    jobsTitle: 'Jobopslag',
    savedJobs: 'Gemte job',
    createJob: 'Opret jobopslag',
    jobTitle: 'Jobtitel',
    jobLocation: 'Lokation',
    jobRemote: 'Remote',
    jobType: 'Ansættelsestype',
    jobTypeFullTime: 'Fuldtid',
    jobTypePartTime: 'Deltid',
    jobTypeFreelance: 'Freelance',
    jobTypeInternship: 'Praktik',
    jobDescription: 'Beskrivelse',
    jobRequirements: 'Krav',
    jobApplyLink: 'Ansøgningslink eller e-mail',
    jobSave: 'Gem job',
    jobSaved: 'Gemt',
    jobApply: 'Ansøg',
    jobPostedBy: 'Opslået af',
    jobNoJobs: 'Ingen jobopslag',
    jobSearchKeyword: 'Søgeord',
    jobSearchLocation: 'Lokation',
    jobSearchType: 'Type',
    jobPost: 'Opslå job',
    // Endorsements (business mode)
    skills: 'Kompetencer',
    addSkill: 'Tilføj kompetence',
    skillPlaceholder: 'f.eks. UX Design, React...',
    endorse: 'Anbefal',
    endorsed: 'Anbefalet',
    endorsements: 'anbefalinger',
    maxSkillsReached: 'Maks. 20 kompetencer nået',
  },
  en: {
    feed: 'Feed',
    profile: 'Profile',
    friends: 'Friends',
    messages: 'Messages',
    navBrand: 'fellis.eu',
    langToggle: 'DA',
    newPost: "What's on your mind?",
    postInputHint: 'Write a post\nEnter → Post  •  Shift+Enter → New line\nPaste images with Ctrl+V',
    msgInputHint: 'Type a message\nEnter → Send  •  Shift+Enter → New line',
    post: 'Post',
    like: 'Like',
    comment: 'Comment',
    share: 'Share',
    writeComment: 'Write a comment...',
    send: 'Send',
    friendsTitle: 'Your friends',
    online: 'Online',
    offline: 'Offline',
    mutualFriends: 'mutual friends',
    message: 'Message',
    editProfile: 'Edit profile',
    joined: 'Member since',
    postsLabel: 'Posts',
    photosLabel: 'Photos',
    friendsLabel: 'Friends',
    loginInfo: 'Login information',
    emailLabel: 'Email',
    loginMethodLabel: 'Login method',
    accountCreatedLabel: 'Account created',
    loginMethodEmail: 'Email & password',
    loginMethodFacebook: 'Facebook',
    passwordLabel: 'Password',
    showPassword: 'Show',
    hidePassword: 'Hide',
    showPasswordHint: 'Show Hint',
    hidePasswordHint: 'Hide Hint',
    passwordNotSet: 'Not set (Facebook login)',
    search: 'Search',
    searchPlaceholder: 'Search your posts and messages...',
    searchHint: 'Search posts you wrote, liked, or commented on, and your conversations.',
    searchPostsTitle: 'Posts',
    searchMessagesTitle: 'Messages',
    searchNoResults: 'No results',
    searchGoToFeed: 'View in feed',
    searchGoToConv: 'Open conversation',
    messagesTitle: 'Messages',
    typeMessage: 'Type a message...',
    noMessages: 'Select a conversation to start',
    newMessage: 'New message',
    newGroup: 'New group',
    newConvTitle: 'New message',
    newGroupTitle: 'Create group',
    groupNamePlaceholder: 'Group name (optional)...',
    startConv: 'Start conversation',
    createGroup: 'Create group',
    invitePeople: 'Add people',
    inviteTitle: 'Add to conversation',
    inviteBtn: 'Add',
    muteConv: 'Mute notifications',
    unmuteConv: 'Unmute notifications',
    muteTitle: 'Mute notifications for...',
    mute1h: '1 hour',
    mute8h: '8 hours',
    mute24h: '24 hours',
    mute1w: '1 week',
    muteOff: 'Turn off',
    mutedLabel: 'Muted',
    renameGroup: 'Rename group',
    renameTitle: 'Rename group',
    renameBtn: 'Save',
    leaveGroup: 'Leave group',
    leaveConfirm: 'Are you sure you want to leave this group?',
    participants: 'participants',
    addedToGroup: 'Added to group',
    familyGroup: 'Family group',
    familyGroupToggle: 'Mark as Family group',
    familyGroupInfo: 'Invite-only · Hidden from search · Posts not shareable outside group',
    familyBadge: '🏡 Family',
    familySection: 'Family',
    familySectionDesc: 'Visible only to accepted family connections',
    familyNoGroups: 'No family groups yet. Create a group and mark it as Family.',
    familyPostNotShareable: 'Posts from family groups cannot be shared outside the group.',
    selectFriends: 'Select friends',
    cancel: 'Cancel',
    convMenu: 'Conversation settings',
    allFriends: 'All friends',
    onlineFriends: 'Online',
    searchFriends: 'Search for users...',
    addFriend: 'Add friend',
    friendAdded: 'Friend added',
    findPeople: 'Find people',
    connectRequest: 'Send connection request',
    requestSent: 'Request sent',
    requestReceived: 'Wants to connect',
    acceptRequest: 'Accept',
    declineRequest: 'Decline',
    incomingRequests: 'Connection requests',
    unfriend: 'Unfriend',
    unfriendConfirm: 'Remove as friend?',
    unfriendSilent: 'Remove silently (no message)',
    unfriendNotify: 'Remove and send a message',
    backToLanding: 'Back to landing',
    // Account mode
    modeTitle: 'Choose account type',
    modeCommon: 'Personal',
    modeBusiness: 'Business',
    modeCommonDesc: 'For personal use, family, and community',
    modeBusinessDesc: 'For professional networking and company presence',
    modeSelect: 'Select',
    modeSwitch: 'Switch account type',
    modeCurrentLabel: 'Account type',
    modeCommonTag: 'Personal account',
    modeBusinessTag: 'Business account',
    // Business-mode labels (Friends → Connections)
    connectionsTitle: 'Your connections',
    connectionsLabel: 'Connections',
    allConnections: 'All connections',
    connectBtn: 'Connect',
    // Business profile fields
    titleLabel: 'Title',
    companyLabel: 'Company',
    industryLabel: 'Industry',
    skillsLabel: 'Skills',
    // Notifications
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No notifications',
    notifFriendRequest: 'sent you a friend request',
    notifConnectionRequest: 'sent you a connection request',
    notifLike: 'liked your post',
    notifComment: 'commented on your post',
    notifAccepted: 'accepted your friend request',
    notifConnectionAccepted: 'accepted your connection request',
    notifGroupPost: 'shared a new post in',
    notifProfileView: 'viewed your profile',
    notifEndorsement: 'endorsed your skills',
    // Events
    events: 'Events',
    eventsTitle: 'Events',
    myEvents: 'My events',
    discoverEvents: 'Discover',
    createEvent: 'Create event',
    eventGoing: 'Going',
    eventMaybe: 'Maybe',
    eventNotGoing: 'Not going',
    eventAttendees: 'attendees',
    eventMaybes: 'maybe',
    eventLocation: 'Location',
    eventDate: 'Date & time',
    eventDescription: 'Description',
    eventCover: 'Cover image (optional)',
    eventTitle: 'Title',
    eventCreate: 'Create event',
    eventCancel: 'Cancel',
    eventRsvp: 'RSVP',
    eventOrganizer: 'Organiser',
    eventShare: 'Share event',
    eventNoUpcoming: 'No upcoming events',
    // Common-mode RSVP extras
    eventDietary: 'Dietary needs (optional)',
    eventPlusOne: 'Bring one guest (+1)',
    // Business-mode event fields
    eventType: 'Event type',
    eventTypeConference: 'Conference',
    eventTypeWebinar: 'Webinar',
    eventTypeWorkshop: 'Workshop',
    eventTypeMeetup: 'Meetup',
    eventTicketUrl: 'Registration link / tickets',
    eventCap: 'Max. attendees',
    eventCapPlaceholder: 'No limit',
    // Feed event card
    eventFeedLabel: 'Event',
    eventFeedRsvpd: 'is going',
    eventFeedCreated: 'created an event',
    // Company pages
    companies: 'Company Pages',
    myCompanies: 'My pages',
    followingCompanies: 'Following',
    createCompany: 'Create company page',
    companyName: 'Company name',
    companyTagline: 'Tagline',
    companyWebsite: 'Website',
    companyIndustry: 'Industry',
    companySize: 'Size',
    companyDescription: 'Description',
    companyFollow: 'Follow',
    companyUnfollow: 'Unfollow',
    companyFollowers: 'followers',
    companyPosts: 'Posts',
    companyAbout: 'About',
    companyRoleOwner: 'Owner',
    companyRoleAdmin: 'Admin',
    companyRoleEditor: 'Editor',
    companyRoleViewer: 'Viewer',
    companyPost: 'Write a post...',
    companySizes: ['1–10', '11–50', '51–200', '201–500', '500+'],
    companyCreate: 'Create page',
    companyCancel: 'Cancel',
    companySearchPlaceholder: 'Search companies...',
    companyFeedLabel: 'Company page',
    // Jobs (business mode)
    jobs: 'Jobs',
    jobsTitle: 'Job listings',
    savedJobs: 'Saved jobs',
    createJob: 'Post a job',
    jobTitle: 'Job title',
    jobLocation: 'Location',
    jobRemote: 'Remote',
    jobType: 'Employment type',
    jobTypeFullTime: 'Full-time',
    jobTypePartTime: 'Part-time',
    jobTypeFreelance: 'Freelance',
    jobTypeInternship: 'Internship',
    jobDescription: 'Description',
    jobRequirements: 'Requirements',
    jobApplyLink: 'Application link or email',
    jobSave: 'Save job',
    jobSaved: 'Saved',
    jobApply: 'Apply',
    jobPostedBy: 'Posted by',
    jobNoJobs: 'No job listings',
    jobSearchKeyword: 'Keyword',
    jobSearchLocation: 'Location',
    jobSearchType: 'Type',
    jobPost: 'Post job',
    // Endorsements (business mode)
    skills: 'Skills',
    addSkill: 'Add skill',
    skillPlaceholder: 'e.g. UX Design, React...',
    endorse: 'Endorse',
    endorsed: 'Endorsed',
    endorsements: 'endorsements',
    maxSkillsReached: 'Max 20 skills reached',
  },
}

// Fake message threads
export const MESSAGE_THREADS = [
  {
    friend: 'Magnus Jensen',
    messages: [
      { from: 'Magnus Jensen', text: { da: 'Hey! Skal vi mødes til kaffe i morgen?', en: 'Hey! Shall we meet for coffee tomorrow?' }, time: '14:23' },
      { from: 'Sofie Nielsen', text: { da: 'Ja, det lyder perfekt! Hvor?', en: 'Yes, that sounds perfect! Where?' }, time: '14:25' },
      { from: 'Magnus Jensen', text: { da: 'Den nye café på Vesterbro? Kl 10?', en: 'The new café in Vesterbro? At 10?' }, time: '14:26' },
      { from: 'Sofie Nielsen', text: { da: 'Ses der! ☕', en: 'See you there! ☕' }, time: '14:27' },
    ],
    unread: 0,
  },
  {
    friend: 'Clara Johansen',
    messages: [
      { from: 'Clara Johansen', text: { da: 'Har du set den nye udstilling på Louisiana?', en: 'Have you seen the new exhibition at Louisiana?' }, time: '11:02' },
      { from: 'Sofie Nielsen', text: { da: 'Nej, er den god?', en: "No, is it good?" }, time: '11:15' },
      { from: 'Clara Johansen', text: { da: 'Den er fantastisk! Vi skal derhen sammen!', en: "It's amazing! We should go together!" }, time: '11:16' },
    ],
    unread: 1,
  },
  {
    friend: 'Emil Larsen',
    messages: [
      { from: 'Emil Larsen', text: { da: 'Tillykke med det nye projekt! 🎉', en: 'Congrats on the new project! 🎉' }, time: '09:45' },
      { from: 'Sofie Nielsen', text: { da: 'Tak! Det har været et langt forløb.', en: 'Thanks! It has been a long process.' }, time: '09:50' },
    ],
    unread: 0,
  },
  {
    friend: 'Alma Hansen',
    messages: [
      { from: 'Alma Hansen', text: { da: 'Kan du anbefale en god podcast?', en: 'Can you recommend a good podcast?' }, time: 'I går' },
    ],
    unread: 1,
  },
]
